<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <joint name="camera_joint" type="fixed">
        <parent link="chassis"/>
        <child link="cam_frame"/>
        <origin xyz="${camera_x} ${camera_y} ${camera_z}" rpy="0 0 0"/>
    </joint>

    <link name="cam_frame">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${camera_length}" y="${camera_width}" z="${camera_height}">
            <origin xyz="0 0 ${camera_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>



    <gazebo reference="cam_frame">
        <sensor name="Camera" type="camera">
            <!-- 
            https://en.wikipedia.org/wiki/PlayStation_Eye
            -->
            <pose relative_to="camera_joint">0.015 0 0 0 0 0</pose>
            <always_on>1</always_on>
            <update_rate>10</update_rate>
            <topic>/gz_camera/image_raw</topic>
            <camera>
            <horizontal_fov>1.3</horizontal_fov>
            <image>
                <width>640</width>
                <height>480</height>
                <format>R8G8B8</format>
            </image>
            <clip>
                <near>0.1</near>
                <far>1000</far>
            </clip>
            <distortion>
                <k1>-0.383727</k1>
                <k2>0.524611</k2>                
                <p1>0.007938</p1>
                <p2>0.033545 </p2>
                <k3>1.991965</k3>
                <center>0.5 0.5</center>
            </distortion>
            </camera>
            <enable_metrics>true</enable_metrics>
        </sensor>
    </gazebo>

</robot>